SanalMarket/Areas/Admin/Controllers/UrunlerController.cs
using SanalMarket.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SanalMarket.Areas.Admin.Controllers
{
    public class UrunlerController : AdminBaseController
    {
        // GET: Urunler
        public ActionResult Index()
        {
            return View(db.Urunler.ToList());
        }

        //GET: Urunler/Ekle
        public ActionResult Ekle()
        {
            ViewBag.KategoriId = new SelectList(db.Kategoriler.ToList(), "Id", "KategoriAd");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Ekle(Urun urun, HttpPostedFileBase dosya)
        {
            if (ModelState.IsValid)
            {
                //Dosya Kaydetme Kısmı

                if (dosya != null && dosya.ContentLength > 0)
                {
                    var ext = Path.GetExtension(dosya.FileName);

                    string[] allowedExtensions = { ".jpg", ".jpeg", ".png", ".gif" };

                    if (dosya.ContentType.StartsWith("image/") && allowedExtensions.Contains(ext))
                    {
                        string yeniDosyaAd = Guid.NewGuid().ToString() + ext;

                        string kaydetmeYolu = Server.MapPath("~/img/" + yeniDosyaAd);

                        dosya.SaveAs(kaydetmeYolu);

                        urun.ResimAd = yeniDosyaAd;
                    }
                }

                db.Urunler.Add(urun);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.KategoriId = new SelectList(db.Kategoriler.ToList(), "Id", "KategoriAd");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Sil(int id)
        {
            Urun urun = db.Urunler.Find(id);

            if (urun != null)
            {
                db.Urunler.Remove(urun);
                db.SaveChanges();

                if (!string.IsNullOrEmpty(urun.ResimAd))
                {
                    var resimYolu = Server.MapPath("~/img/" + urun.ResimAd);

                    if (System.IO.File.Exists(resimYolu))
                    {
                        System.IO.File.Delete(resimYolu);
                    }
                }
            }

            return RedirectToAction("Index", new { sonuc = "silindi" });
        }

        public ActionResult Duzenle(int id)
        {
            Urun urun = db.Urunler.Find(id);

            if (urun == null)
            {
                return HttpNotFound();
            }

            ViewBag.KategoriId = new SelectList(db.Kategoriler.ToList(), "Id", "KategoriAd");

            return View(urun);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Duzenle(Urun urun, HttpPostedFileBase dosya)
        {
            if (ModelState.IsValid)
            {
                Urun dbdekiEskiUrun = db.Urunler.Find(urun.Id);

                //Dosya Kaydetme Kısmı

                if (dosya != null && dosya.ContentLength >0 && dosya.ContentLength < 2*1024*1024)
                {
                    // Yüklenen dosya resim mi?

                    var ext = Path.GetExtension(dosya.FileName);

                    string[] allowedExtensions = { ".jpg", ".jpeg", ".png", ".gif" };

                    if (!dosya.ContentType.StartsWith("image/") || !allowedExtensions.Contains(ext))
                    {
                        ModelState.AddModelError("ResimAd", "Geçersiz bir resim dosyası yüklediniz.");
                    }

                    // Eğer Form verilerinde hala hata yoksa

                    if (ModelState.IsValid)
                    {
                        // Yeni dosye geldiğine göre eski dosya varsa silelim

                        if (!string.IsNullOrEmpty(dbdekiEskiUrun.ResimAd))
                        {
                            var dbdekiEskiUrunResimYol = Server.MapPath("~/img/" + dbdekiEskiUrun.ResimAd);

                            if (System.IO.File.Exists(dbdekiEskiUrunResimYol))
                            {
                                System.IO.File.Delete(dbdekiEskiUrunResimYol);
                            }
                        }

                        // Yeni resmin kaydedilmesi

                        string yeniDosyaAd = Guid.NewGuid().ToString() + ext;

                        string kaydetmeYolu = Server.MapPath("~/img/" + yeniDosyaAd);

                        dosya.SaveAs(kaydetmeYolu);

                        dbdekiEskiUrun.ResimAd = yeniDosyaAd;
                    }
                }

                if (ModelState.IsValid)
                {
                    // Gelen ürün bilgilerini DB deki eski ürün bilgilerine aktar.

                    dbdekiEskiUrun.UrunAd = urun.UrunAd;
                    dbdekiEskiUrun.KategoriId = urun.KategoriId;
                    dbdekiEskiUrun.Birimfiyat = urun.Birimfiyat;

                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
            }

            //Gönderilen formda hata varsa aynı verilerle ve hata mesajlarıyla formu tekrar aç.

            ViewBag.KategoriId = new SelectList(db.Kategoriler.ToList(), "Id", "KategoriAd");

            return View(urun);
        }
    }
}

SanalMarket/Areas/Admin/Views/Urunler/Duzenle.cshtml
@model Urun

@{
    ViewBag.Title = "Ürün Düzenle";
}

<div class="container">

    <h2>Ürün Düzenle</h2>

    @using (Html.BeginForm("Duzenle", "Urunler", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(x => x.Id)

        <div class="form-group">
            @Html.LabelFor(x => x.KategoriId)
            @Html.DropDownListFor(x => x.KategoriId, null, "Seçiniz", new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.KategoriId, null, new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.UrunAd)
            @Html.TextBoxFor(x => x.UrunAd, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.UrunAd, null, new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.Birimfiyat)
            @Html.TextBoxFor(x => x.Birimfiyat, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Birimfiyat, null, new { @class = "text-danger" })
        </div>


        var resimAd = string.IsNullOrEmpty(Model.ResimAd) ? "gorselyok.jpg" : Model.ResimAd;


        <div class="form-group">
            @Html.HiddenFor(x => x.ResimAd)
            <label for="dosya">Ürün Resmi</label><br />
            <img src="~/img/@resimAd" height="100" class="mb-2" /><br />
            <input type="file" class="form-control-file" name="dosya" id="dosya" />
            @Html.ValidationMessageFor(x => x.ResimAd, null, new { @class = "text-danger" })
        </div>

        <button type="submit" class="btn btn-success mb-2">Kaydet</button>

    }

</div>

SanalMarket/Areas/Admin/Views/Urunler/Ekle.cshtml
@model Urun

@{
    ViewBag.Title = "Yeni Ürün";
}

<div class="container">

    <h2>Yeni Ürün</h2>

    @using (Html.BeginForm("Ekle", "Urunler", FormMethod.Post, new { enctype= "multipart/form-data"}))
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.LabelFor(x => x.KategoriId)
            @Html.DropDownListFor(x => x.KategoriId, null, "Seçiniz", new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.KategoriId, null, new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.UrunAd)
            @Html.TextBoxFor(x => x.UrunAd, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.UrunAd, null, new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.Birimfiyat)
            @Html.TextBoxFor(x => x.Birimfiyat, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Birimfiyat, null, new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="dosya">Ürün Resmi</label>
            <input type="file" class="form-control-file" name="dosya" id="dosya" />
        </div>

        <button type="submit" class="btn btn-success mb-2" >Kaydet</button>

    }

</div>

SanalMarket/Areas/Admin/Views/Urunler/Index.cshtml
@model List<Urun>

@{
    ViewBag.Title = "Ürünler";
}

<div class="container">

    @*@OnKereTekrarla("Öznur")
        @Basari("Tebrikler! Kazandınız...")*@

    <h2>Ürünler</h2>

    <div class="islemButonlari">

        @Html.ActionLink("Yeni Ürün", "Ekle", "Urunler", null, new { @class = "btn btn-success" })

    </div>

    @if (Request.QueryString["sonuc"] == "silindi")
    {
        <div class="alert alert-info">
            Seçtiğiniz ürün(ler) başarıyla silindi.
        </div>
    }

    <table class="table table-success table-striped" id="tblUrunler">
        <thead>
            <tr>
                <th>Id</th>
                <th>Ürün Görseli</th>
                <th>Ürün Adı</th>
                <th>Birim Fiyatı</th>
                <th>Kategori Adı</th>
                <th>İşlemler</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Urun urun in Model)
            {
                <tr>
                    <td>@urun.Id</td>
                    <td><img src="~/img/@(string.IsNullOrEmpty(urun.ResimAd) ? "gorselyok.jpg" : urun.ResimAd)" width="100" height="100" /></td>
                    <td>@urun.UrunAd</td>
                    <td>@urun.Birimfiyat</td>
                    <td>@urun.Kategori.KategoriAd</td>
                    <td>

                        <a href="@Url.Action("Duzenle", "Urunler", new { Id = urun.Id })" class="btn btn-success">
                            <i class="fas fa-edit"></i>
                        </a>

                        <form action="@Url.Action("Sil", "Urunler")" method="post" class="SilForm">
                            @Html.AntiForgeryToken()
                            <input type="hidden" name="Id" value="@urun.Id" />
                            <button type="submit" class="btn btn-danger">
                                <i class="fas fa-trash"></i>
                            </button>
                        </form>

                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

@section styles {

    <link href="~/Areas/Admin/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" />

}

@section scripts
{
    <script src="~/Areas/Admin/vendor/datatables/jquery.dataTables.min.js"></script>

    <script src="~/Areas/Admin/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <script>

        $("#tblUrunler").DataTable();

        $("form.SilForm").submit(function () {
            return confirm("Silmek istediğinize emin misiniz?");
        });
    </script>
}


@*@helper OnKereTekrarla(string isim)
    {
        for (int i = 0; i < 10; i++)
        {
            @isim <br />
        }
    }

    @helper Basari(string mesaj)
    {
        <div class="alert alert-success" role="alert">
            @mesaj
        </div>
    }*@